let perros= [
    {
        "id":1,
        "raza":"Bichón Boloñés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/u_pKHWsBIYfdNSoCOxqf/v1/bd33bl-hub-bolognese-adult-standing?w=320&auto=compress&fm=jpg",
        "imagen":"https://cdn.royalcanin-weshare-online.io/vfpNHWsBIYfdNSoCqRqj/v1/bd33h-hub-bolognese-black-and-white?w=640&auto=compress&fm=jpg",
        "descripcion":"Estos perros muy serios son tranquilos, apacibles y muy apegados a sus compañeros humanos.",
        "acercade":"Estos perros tan entrañables, que tienen una expresión tan seria, son conocidos por su inteligencia, naturaleza observadora y disposición tranquila. La personalidad cómica y naturaleza curiosa los convierten en perros familiares muy queridos. Ya sea acurrucado en casa o paseando, el bichón boloñés es un perro devoto al que lo que más le gusta es estar cerca de la familia humana.Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Muy Pequeño",
        "vida":"12-14 años"
    },
    {
        "id":2,
        "raza":"Bichón maltés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/0mksHWsBG95Xk-RBvfih/v1/bd16bl-hub-maltese-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/KWnuW2gBG95Xk-RB69-d/v2/maltese-adult-emblematic?w=640&h=640&auto=compress&fm=jpg&auto=compress",
        "descripcion":"Animados, afectuosos y muy inteligentes, los bichones malteses son excelentes perros de compañía.",
        "acercade":"Los bichones malteses son amistosos y dóciles, y saludarán a las personas con confianza. Durante siglos han sido criados como compañeros y nunca son más felices que cuando están sentados en el regazo de su dueño. A pesar del nombre, los perros de esta raza no son de Malta en absoluto. La palabra deriva de una palabra en uno de los idiomas mediterráneos para refugio o puerto, que simplemente también es la raíz de la palabra Malta. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Muy pequeño",
        "vida":"12-15 años"
    },
    {
        "id":3,
        "raza":"Chihuahua",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/lPqsHGsBIYfdNSoCrxqw/v1/bd6bl-hub-chihuahua-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/x2mtHGsBG95Xk-RBmPhV/v1/bd6h-hub-chihuahua-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"La idea generalizada es que el Chihuahua es la raza de perros de pedigrí más pequeña del mundo.",
        "acercade":"Hay dos variedades distintas de la raza: el de pelo corto y el de pelo largo. Cada una posee su propio temperamento distintivo. Los Chihuahua pueden ser muy fieles a una persona. Debido a su tamaño y constitución frágil, es importante asegurarse de enseñar a los niños cómo manejarlos correctamente. Su temperamento puede variar drásticamente, y algunos son particularmente difíciles de entrenar. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"México",
        "tamaño":"Muy pequeño",
        "vida":"14-18 años"
    },
    {
        "id":4,
        "raza":"Petit brabançon",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/yWnxsmoBG95Xk-RBivYQ/v1/bd264bl-hub-petit-brabancon-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/ymnxsmoBG95Xk-RB8faX/v1/bd264h-hub-petit-brabancon-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los petit brabançon son famosos por su naturaleza dulce, juguetona y divertida.",
        "acercade":"Dada su sensibilidad, estos perros no responden bien a un entrenamiento y conducta riguroso y, a menudo, pueden parecer un poco temperamentales cuando no están a gusto. Son excelentes perros de compañía y desarrollan vínculos muy estrechos con sus dueños. A pesar de su pequeña estatura, necesitan realizar una cantidad moderada de ejercicio al día. Algunos rasgos típicos de los terriers los convierten en perros muy aventureros, a los que les gusta explorar su entorno. Se recomiendan jardines grandes y seguros para esta raza. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Bélgica",
        "tamaño":"Muy pequeño",
        "vida":"12-15 años"
    }, 
    {
        "id":5,
        "raza":"Pomerano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/tSEpa2QBaxEApS7Lf_dz/v2/pomranien-pomeranian?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/wT-zSnIBRYZmsWpcbHGt/v1/pomeranian-adult?w=640&fm=jpg&auto=compress",
        "descripcion":"Una gran personalidad en un cuerpo pequeño.",
        "acercade":"Los Pomeranos son famosos por sus hermosos pelajes, que se destacan al sobresalir de una subcapa gruesa. El marcado collar en forma de melena que se les forma alrededor del cuello (gorguera) y la cola espesa, que se yergue airosa sobre la espalda para completar la silueta, son particularmente impresionantes. La cabeza atractiva, con mirada alerta y pequeñas orejas puntiagudas y muy juntas, les da a los Pomeranos su aspecto único y su encanto tan característico. Los Pomeranos siempre están atentos, y son animados y extraordinariamente devotos a su dueño. Aprenden rápido, por lo que son fáciles de entrenar. A pesar de tener un tamaño pequeño, esta raza conservó la inteligencia y la fortaleza mental de sus ancestros nórdicos, por lo que es importante establecer los límites correctos desde el principio. El carácter afable y alegre del Pomerano lo convierte en el compañero ideal, un buen perro de familia y un perro guardián para el hogar. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Muy pequeño",
        "vida":"12-16 años"
    },
    {
        "id":6,
        "raza":"Spaniel Continental Enano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/T_qwH2YBIYfdNSoCrgjO/v2/bd171bl-continental-toy-spaniel-adult-lying-down?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/2SIrxWoBaxEApS7LtRsi/v1/bd171h-hub-continental-toy-spaniel-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Estos perros bien equipados, nativos de la antigua región de Flandes, son compañeros maravillosos y muy populares. Solían ser los favoritos de las cortes reales, en especial la variedad papillon.",
        "acercade":"Los Spaniel Continental Enano son perros pequeños de complexión normal y armoniosa y pelo largo. Hay dos variedades: Phalene y Papillon. Estos spaniels son animados y elegantes, pero robustos; se mueven con orgullo, distinción y desenvoltura. El hocico es un poco largo, pero más corto que el cráneo. El cuerpo es un poco más largo que la altura de la cruz. Las orejas son una característica distintiva del Spaniel Continental Enano. En el phalene, están muy por encima del nivel de los ojos; tienen caída, pero son móviles. En el papillon, las orejas son altas; la aurícula está muy abierta y se ubica de lado. Cualquiera sea la variedad, las orejas nunca deben apuntar hacia arriba como un Spitz. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Muy pequeño",
        "vida":"12-15 años"
    },
    {
        "id":7,
        "raza":"Spaniel japonés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/GCInx2oBaxEApS7Ljxxf/v1/bd79bl-hub-japanese-chin-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/Lfopx2oBIYfdNSoCBRkq/v1/bd79h-hub-japanese-chin-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los spaniel japoneses son miembros de una raza alerta, dócil y encantadora, por lo que resultan excelentes compañeros. Su personalidad curiosa e inteligente se refleja en su expresión.",
        "acercade":"Los spaniels japoneses son conocidos por ser amorosos y graciosos perros falderos. Estos perros son afectuosos con sus dueños y solo quieren estar a su lado. A pesar de su pequeño tamaño, estos perros tienen personalidades llamativas y bulliciosas, y mucha energía. Su inteligencia, junto con su adaptabilidad y amor por sus familias humanas, los ha convertido en compañeros populares en todo el mundo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Japón",
        "tamaño":"Muy pequeño",
        "vida":"10-12 años"
    },
    {
        "id":8,
        "raza":"Terrier sedoso australiano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/KyIwx2oBaxEApS7LbBxr/v1/bd105bl-hub-australian-silky-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/LCIwx2oBaxEApS7LmhxS/v1/bd105h-hub-australian-silky-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El terrier sedoso australiano es un perro compacto, bastante bajo, pero con la presencia suficiente como para atrapar y acabar a los roedores de la casa.",
        "acercade":"Los terrier sedosos son nativos de Sídney, Australia, y están estrechamente relacionados con el yorkshire terrier. Su pelaje es fino, liso y lustroso, y es lo que les da su nombre. A pesar de su tamaño y apariencia refinada, estos perros tienen todas las características del terrier, incluida agudeza, actividad y solidez. Estos pequeños y alegres perros son excelentes compañeros gracias a su naturaleza sociable y adaptabilidad. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Australia",
        "tamaño":"Muy pequeño",
        "vida":"12-15 años"
    },
    {
        "id":9,
        "raza":"Yorkshire terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/DSIIHWsBaxEApS7Lqx3G/v1/bd9bl-hub-yorkshire-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/DiIIHWsBaxEApS7L-h1o/v1/bd9h-hub-yorkshire-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Resueltos y llenos de carácter, los yorkshire terrier son excelentes perros de compañía.",
        "acercade":"El yorkshire terrier tiene un magnífico pelaje que requiere de aseo regular. A pesar de su apariencia de perro miniatura, sigue siendo un terrier de corazón y conserva su instinto de caza, ya sea por un juguete en la casa o un roedor en el jardín. Los yorkshire terrier no siempre se llevan bien con los niños, en especial con los activos y ruidosos. Los instintos dominantes de este terrier a veces pueden ser un desafío para otras mascotas y perros. Sin embargo, el temperamento de un perro a menudo es producto de su entrenamiento y crianza, por lo que los yorkshire terrier pueden ser excelentes mascotas familiares cuando están bien entrenados. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Muy pequeño",
        "vida":"15-16 años"
    },
    {
        "id":10,
        "raza":"Basset Leonado de Bretaña",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/AiLQxWoBaxEApS7L7Bxa/v1/bd138bl-hub-basset-fauve-de-bretagne-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/7vrzHWsBIYfdNSoCURp4/v9/bd138h-hub-basset-fauve-de-bretagne-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El Basset Leonado de Bretaña es un perro pequeño y compacto. Animado y rápido, combina una energía extraordinaria con una resistencia excepcional.",
        "acercade":"Además de cazadores apasionados, los perros de esta raza son excelentes compañeros para las personas y son valorados por su sociabilidad, afecto y equilibrio. Les es fácil adaptarse a cualquier juego y cualquier terreno. Durante la caza, son valientes, astutos y obstinados, lo cual es una muy buena receta para la eficiencia. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Pequeño",
        "vida":"11-14 años"
    },
    {
        "id":11,
        "raza":"Bedlington Terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/DCLUxWoBaxEApS7LIRwL/v3/bd143bl-hub-bedlington-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/BiLSxWoBaxEApS7LpRyv/v1/bd143h-hub-bedlington-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Estos compañeros inteligentes poseen sólidos instintos de caza.",
        "acercade":"A pesar de su exterior tranquilo y vigilante, los Bedlington Terrier pueden correr a gran velocidad. Los Bedlington Terrier son perros elegantes y musculosos sin ningún signo de debilidad ni aspereza. Debido a su carácter poco exigente, son fáciles de criar y educar, y son populares entre las familias por su naturaleza tranquila y devota. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"14-16 años"
    },
    {
        "id":12,
        "raza":"Bichón frisé",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/4GlFHWsBG95Xk-RB8fhT/v1/bd31bl-hub-bichon-frise-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/4mlHHWsBG95Xk-RBsPjz/v1/bd31h-hub-bichon-frise-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Inteligente, vivaz y bastante enérgico, el bichón frisé es una adición fantástica a cualquier familia.",
        "acercade":"Los bichones frisé tienen todas las cualidades físicas y de conducta del perro compañero ideal, y no menos que una gran disposición para compartir su cariño. Se han convertido en un perro de compañía muy popular en todo el mundo. Los bichones frisé son perritos animados, de ojos expresivos, y un carácter alegre y juguetón. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":13,
        "raza":"Bichón habanero",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/MyLgHWsBaxEApS7LnR1b/v1/bd72bl-hub-havanese-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/NCLgHWsBaxEApS7L8h10/v1/bd72h-hub-havanese-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Naturalmente alegre, amistoso, encantador e incluso, un poco bufón, al bichón habanero le encanta jugar.",
        "acercade":"El bichón habanero es un perro robusto con patas cortas y un andar muy activo. Tienen un pelaje suave, largo y abundante que, a menudo, es ondulado. Estos perros son amorosos y afectuosos con sus dueños y prefieren estar a su lado durante todo el día. El bichón habanero es un perro alerta que notificará a sus dueños sobre extraños que se acerquen, por lo que serán excelentes perros guardianes. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Cuba",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":14,
        "raza":"Border terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/6GlPHWsBG95Xk-RBdPjR/v1/bd35bl-hub-border-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/6WlQHWsBG95Xk-RBUviL/v1/bd35h-hub-border-terrier-adult-black-and-white?w=640&h=480&auto=compress&fm=jpg&auto=compress",
        "descripcion":"Los border son indudablemente todo terrier. Nada asusta a estos pequeños y orgullosos perros.",
        "acercade":"De estructura sólida, bien equilibrados y llenos de energía, los border terriers son intrépidos. Esta raza tiene todos los rasgos de conducta de un perro de trabajo. Antes de ser reconocidos por el Kennel Club, los border terrier a menudo tenían que alimentarse solos y solo aquellos que eran cazadores naturales se procuraban suficiente alimento. En gran medida, esto explica el carácter de la raza. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":15,
        "raza":"Bull Terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/-mlZHWsBG95Xk-RB9fgV/v5/bd43bl-hub-bull-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/-2laHWsBG95Xk-RBd_jN/v1/bd43h-hub-bull-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los Bull Terrier son perros dedicados y valientes que son nada menos que los gladiadores del mundo canino.",
        "acercade":"Disciplinados y apacibles, los Bull Terrier son especialmente buenos con las personas y se adaptan bien como compañeros para la familia. Robustos, bien equilibrados y activos, los Bull Terrier tienen una expresión animada, terca e inteligente. En acción, los Bull Terrier lucen bien tenidos y se mueven con zancadas regulares, despreocupadas y simples, con una agilidad característica. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"11-14 años"
    },
    {
        "id":16,
        "raza":"Cairn terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/AGldHWsBG95Xk-RBvfns/v1/bd45bl-hub-cairn-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/_2lbHWsBG95Xk-RB7vg6/v1/bd45a-hub-cairn-terrier-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Tanto el terrier escocés como el West Highland terrier descienden del cairn terrier, que es animado y seguro de sí mismo.",
        "acercade":"Los cairns son montículos de piedras irregulares construidos como monumentos o puntos de referencia en la cima de las colinas o las pendientes de Escocia. Las alimañas los utilizan para esconderse, y los cairn terriers fueron criados para cazarlas.Los cairn terriers son perros activos y resistentes. Se apoyan con firmeza sobre las patas delanteras y se mueven con mucha soltura y pasos largos, mientras que las patas traseras los empujan con fuerza. Al igual que todos los terrier que trabajan, los cairn tienen un pelaje resistente a la intemperie. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":17,
        "raza":"Carlino",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/wmmiHGsBG95Xk-RBsfhY/v1/bd2bl-hub-pug-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/kPqjHGsBIYfdNSoCARqo/v8/pug-for-hub?w=640&fm=jpg&auto=compress",
        "descripcion":"El carlino tiene su propio lema latino, 'Multum in Parvo', que simplemente significa: 'Mucho en poco'.",
        "acercade":"El carlino tiene una apariencia única, que muchos encuentran tremendamente atractiva y, como tal, su popularidad aumenta año tras año. Los carlinos tienen un pelaje fácil de mantener, y la raza no necesita realizar muchos ejercicios, lo cual es una ventaja para los dueños ocupados. El carlino, una mascota muy deseada, es conocido por su naturaleza curiosa y enérgica. Es parte del grupo de perros Toy, sin embargo, es único entre este grupo ya que es el único miembro que se cree que comparte su ascendencia con los mastines ingleses. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"China",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":18,
        "raza":"Cavalier King Charles",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/yvphHWsBIYfdNSoCRhpx/v1/bd48bl-hub-cavalier-king-charles-spaniel-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/FiJ8HWsBaxEApS7LTR1p/v1/bd48h-hub-cavalier-king-charles-spaniel-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El cavalier King Charles es deportivo, afectuoso y absolutamente intrépido.",
        "acercade":"Gracias a su naturaleza alegre y amistosa, sin ningún tipo de agresividad, estos perros se hicieron muy populares a fines del milenio anterior.Los cavalier King Charles son activos, elegantes y bien equilibrados. Tienen una expresión particularmente dócil, con grandes ojos oscuros que destilan curiosidad inteligente. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"10-14 años"
    },
    {
        "id":19,
        "raza":"Coton de Tulear",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/HCKLHWsBaxEApS7L1x3Q/v5/bd53bl-hub-coton-de-tulear-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/GiKCHWsBaxEApS7LmR23/v1/bd53h-hub-coton-de-tulear-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los coton de Tulear son apacibles y muy sociables; se adaptan a cualquier estilo de vida a la perfección.",
        "acercade":"El pelaje es una de las principales características de la raza, e incluso es lo que le da el nombre. El pelo, con textura de algodón, es suave y blando. Estos perros tienen ojos oscuros y redondos que expresan vivacidad e inteligencia. Poseen un temperamento feliz y sociable, una de las características principales de la raza. Estos encantadores perritos se vinculan fácilmente con sus dueños y se llevan bien con otros perros. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Madagascar",
        "tamaño":"Pequeño",
        "vida":"14-16 años"
    },
    {
        "id":20,
        "raza":"Dandie Dinmont Terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/GPotxWoBIYfdNSoCHRlP/v1/bd174bl-hub-dandie-dinmont-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/UCIGHmsBaxEApS7Lmx3J/v1/bd174h-hub-dandie-dinmont-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los Dandie Dinmont Terrier se distinguen en que son los únicos perros que llevan el nombre de un personaje de ficción.",
        "acercade":"Llenos de vida, estos trabajadores terriers son perros de compañía independientes, muy inteligentes, tercos, tenaces, sensibles, amorosos y dignos. Su cabeza distintiva tiene una buena capa de pelo suave y grandes ojos llenos que destilan inteligencia y sabiduría. Su cuerpo largo y bajo, que recuerda a una comadreja, presenta un desarrollo sólido, con patas cortas y rechonchas. Dandie Dinmont era un granjero con una manada de esos perros en la novela Guy Mannering de Sir Walter Scott, que se desarrolla en las tierras fronterizas entre Escocia e Inglaterra. Scott también proporcionó los nombres de los colores 'pimienta' y 'mostaza'. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":21,
        "raza":"Fox terrier de pelo liso",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/sWnjsmoBG95Xk-RB9vaD/v1/bd305bl-hub-fox-terrier-smooth-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/sGnismoBG95Xk-RBlPaZ/v5/bd305h-hub-fox-terrier-smooth-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los fox terrier de pelo liso se criaron como respuesta ante la incapacidad de los foxhound para perseguir a los zorros hasta su escondite y hacerlos salir. Después de varias cruzas, se produjo un perro pequeño para completar esta tarea.",
        "acercade":"Los fox terrier de pelo liso son perros activos y animados que siempre están atentos y alertas ante cualquier desafío. Son amistosos, sociables y audaces. Como su nombre lo indica, su función principal era rastrear y atrapar a los zorros. Ya sea que se usen para cazar o no, a los fox terriers de pelo liso les encanta correr, excavar y explorar, y por eso son los más adecuados para las familias activas. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":22,
        "raza":"Grifón de Bruselas",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/-GlZHWsBG95Xk-RBQ_jY/v1/bd42bl-hub-griffon-bruxellois-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/-WlZHWsBG95Xk-RBpvhW/v1/bd42h-hub-griffon-bruxellois-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Con una personalidad inteligente y entusiasta, el grifón de Bruselas se ha ganado a los amantes de los perros en todo el mundo.",
        "acercade":"Originario de Bélgica como cazarratones, el grifón de Bruselas pronto se convirtió en una mascota muy querida. A veces muy tenso, sensible y a menudo el centro de atención, esta raza requiere un dueño que esté dispuesto a dedicar su tiempo completamente a su nuevo compañero. Aunque pequeño, el grifón de Bruselas no es en absoluto un perro para llevar en un bolso; por el contrario, esta raza robusta gusta del entrenamiento de agilidad y obediencia, y a menudo se destaca en los deportes de rendimiento. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Bélgica",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":23,
        "raza":"Grifón belga",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/dvrNsmoBIYfdNSoCKBiq/v1/bd209bl-hub-griffon-belge-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/kGnNsmoBG95Xk-RBXPZG/v1/bd209h-hub-griffon-belge-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los grifones tienen el pelo áspero, erguido y despeinado, con un crecimiento más largo debajo de los ojos, en el hocico, las mejillas y la barbilla, lo que forma el pelaje distintivo de la cabeza.",
        "acercade":"Estos perros inteligentes y bien equilibrados son alertas, orgullosos y robustos. Prácticamente cuadrados, tienen una buena estructura ósea y, a pesar de todo, son elegantes y se mueven con gracia. Su expresión casi humana llama la atención. Ni tímidos ni agresivos, siempre están muy atentos y son muy apegados a su compañero humano. All the three breeds (Griffon Bruxellois, Griffon Belge and Petit Brabançon are descended from a small rough-coated dog that went by the name Smousje, which had been found in the Brussels region for centuries. Estos perros pequeños eran criados para proteger los carruajes y mantener a los establos libres de roedores. Ambos grifones tienen un pelaje áspero y se pueden distinguir por el color, mientras que el petit brabançon tiene el pelo corto. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Bélgica",
        "tamaño":"Pequeño",
        "vida":"12-15 años"
    },
    {
        "id":24,
        "raza":"Lakeland terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/omnWsmoBG95Xk-RBU_bA/v1/bd240bl-hub-lakeland-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/o2nWsmoBG95Xk-RBjvah/v1/bd240h-hub-lakeland-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los lakeland terrier son arduos trabajadores, observadores e inteligentes, que resultan compañeros alegres y amistosos.",
        "acercade":"Seguros de sí mismos y audaces, y con una expresión aguda, estos perros compactos se mueven muy rápido. Desarrollado para correr con manadas de sabuesos sobre el terreno escarpado y rocoso de Lake District, el lakeland terrier es muy seguro en su andar, ágil y está lleno de energía. Negro con canela es el color más común para los lakeland terriers, pero también hay una variedad negra. Desapareció en Gran Bretaña, pero los criadores escandinavos lo han reintroducido en la población. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Pequeño",
        "vida":"12-16 años"
    },
    {
        "id":25,
        "raza":"Lundehund Noruego",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/j_rbsmoBIYfdNSoCeRg1/v1/bd254bl-hub-norwegian-lundehund-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/bmmEMWsBG95Xk-RBN_k4/v1/bd254h-hub-norwegian-lundehund-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Existen menos de 3000 Lundehund Noruego en el mundo, lo que los convierte en una de las razas raras.",
        "acercade":"Los Lundehund Noruego son perros de tipo Spitz, con cuerpos rectangulares y contextura bastante ligera y flexible. Alertas, enérgicos y activos, los Lundehund Noruego están perfectamente adaptados para cazar frailecillos en fiordos rocosos y litorales.Proceden de las Islas Lofoten, que se encuentran frente a la ciudad de Bodø, al norte del Círculo Polar Ártico. Estos perros pequeños se criaron especialmente para los cazadores de frailecillos. Su población disminuyó drásticamente después de que se prohibió esta práctica. La raza moderna tiene base en solo cinco ejemplares, lo que explica su notable homogeneidad. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Noruega",
        "tamaño":"Pequeño",
        "vida":"12-14 años"
    },
    {
        "id":26,
        "raza":"Mudi",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/jfrZsmoBIYfdNSoCxBix/v5/bd249bl-hub-mudi-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/YyIdHmsBaxEApS7LSR0W/v3/bd249h-hub-mudi-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los mudis son elogiados por su naturaleza extraordinariamente laboriosa y por su temperamento animado, valiente, atento, diligente, alerta y servicial.",
        "acercade":"Notablemente ágiles, además de realizar tareas de vigilancia y alarma, son muy buenos olfateando narcóticos. El mudi tiene un pelaje bastante corto y suave en la cabeza y las patas, mientras que el resto del cuerpo tiene un pelaje más largo, ondulado o ligeramente rizado. Esta raza amorosa se puede tener en el interior sin ningún problema, y son perros familiares entrañables. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Hungría",
        "tamaño":"Pequeño",
        "vida":"13-14 años"
    },
    {
        "id":27,
        "raza":"Airedale Terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/rfozHWsBIYfdNSoCiRpm/v1/bd21bl-hub-airedale-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/rPozHWsBIYfdNSoCGBr4/v1/bd21h-hub-airedale-terrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El Airedale Terrier es ampliamente conocido por ser el terrier más grande.",
        "acercade":"Los Airedales son robustos y están siempre alerta, no son agresivos ni se asustan fácilmente. Es un perro activo y musculoso, con expresiones profundas y una naturaleza muy amistosa. El Airedale Terrier es conocido por ser una de las razas más versátiles del mundo y se ha ganado una reputación de cazador, atleta y compañero. En algunos países, se suele utilizar como perro policía. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Mediano",
        "vida":"10-13 años"
    },
    {
        "id":28,
        "raza":"American Staffordshire terrier",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/8iLJxWoBaxEApS7L-RuR/v3/bd126bl-hub-american-staffordshire-terrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/OiLoHWsBaxEApS7LKR24/v1/bd126h-hub-american-staffordshire-terrie-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los American Staffordshire terriers son excelentes guardianes, debido a su inteligencia y lealtad.",
        "acercade":"El American Staffordshire terrier, fuerte, atlético y valiente, es ideal para entrenamientos de obediencia y agilidad. El American Staffordshire terrier es una raza muy afectuosa y sociable con las personas. Ama pasar el tiempo con su compañero humano. Esta raza es amante de la diversión y ha pasado de ser un antiguo ancestro del pit bull terrier a ser un perro familiar mucho más dócil que se lleva bien con otras mascotas, niños y adultos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Estados Unidos",
        "tamaño":"Mediano",
        "vida":"12-14 años"
    },
    {
        "id":29,
        "raza":"Ariegeois",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/22k9HWsBG95Xk-RBlfiM/v1/bd26bl-hub-ariegeois-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/tPo-HWsBIYfdNSoCPBqV/v3/bd26h-hub-ariegeois-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Si bien los Ariegeois son famosos por cazar liebres, también se utilizan para rastrear corzos y jabalíes.",
        "acercade":"Los Ariegeois son perros trabajadores, muy inteligentes y resistentes, lo que los convierte en excelentes perros de caza. Tienen una personalidad alegre y sociable; los caracteriza una lealtad inquebrantable. El Ariegeois tiene las características físicas de un sabueso. Es famoso por sus habilidades, su obediencia, ya sea solo o en manada, y su agilidad en terrenos difíciles. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"10-12 años"
    },
    {
        "id":30,
        "raza":"Barbet",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/ACLQxWoBaxEApS7LhxxY/v3/bd135bl-hub-barbet-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/PSLtHWsBaxEApS7LzB2W/v1/bd135h-hub-barbet-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Las barbet son apacibles, muy sociables y muy apegados a su amo o ama.",
        "acercade":"Al igual que todos los perros de agua, los barbet, que se utilizan para cazar aves silvestres, son más que simples perros perdigueros. Saben localizar y hacer salir a la presa que se esconde en la vegetación acuática y la pueden recuperar una vez que le han disparado. Sin miedo al frío, entran al agua sin importar las condiciones climáticas. Su medio favorito es el agua, la cual estarán felices de salpicar por trabajo o placer. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"13-15 años"
    },
    {
        "id":31,
        "raza":"Basenji",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/tfo_HWsBIYfdNSoC7xo7/v1/bd28bl-hub-basenji-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/3WlAHWsBG95Xk-RByvhQ/v5/bd28h-hub-basenji-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los basenjis no ladran, sino que emiten un tipo muy particular de 'canto yodel'.",
        "acercade":"Los basenjis son perros de contextura delgada y huesos finos con patas largas, siempre bien equilibrados, animados e inteligentes. Aunque es relativamente independiente y distante con los extraños, el basenji es conocido por ser afectuoso con su familia. Estos perros notablemente limpios son activos y de movimiento grácil, ya que exhiben zancadas largas y suaves. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Congo",
        "tamaño":"Mediano",
        "vida":"12-16 años"
    },
    {
        "id":32,
        "raza":"Basset artesiano de Normandía",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/ASLQxWoBaxEApS7Lwxzg/v1/bd136bl-hub-basset-artesien-normand-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/AyLRxWoBaxEApS7LNRwb/v1/bd136h-hub-basset-artesien-normand-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los basset artesianos de Normandía son perros tenaces y de potente ladrido, con una nariz muy fina y que no tiran demasiado fuerte en la línea siguiendo el rastro de su marca.",
        "acercade":"Los basset artesianos de Normandía son perros de tamaño pequeño, utilizados por cazadores, que pueden trabajar solos o en grupo. Sus patas cortas les permiten penetrar en vegetación muy densa, esa que está fuera del alcance de perros más grandes, para hacer salir la presa. Les gusta cazar conejos, pero las liebres y los corzos también están dentro de sus capacidades. Rastrean y hacen salir las presas con gran seguridad, no de forma rápida, sino metódica y ruidosamente. Son naturalmente alegres y muy afectuosos. Cuando asumió el liderazgo del club de criadores en 1927, Léon Verrier expresó el deseo de fortalecer el carácter normando de la raza, en contraste con el sabueso artesiano. En el libro de estándares publicado tres años más tarde, por lo tanto, se declaró que el 'basset artesiano de Normandía debe estar a un solo paso de un tipo normando, sin rastro de artesiano'. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":33,
        "raza":"Beagle",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/xmmpHGsBG95Xk-RB5vhT/v1/bd5bl-hub-beagle-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/oGl6DmcBG95Xk-RB0t7-/v2/dog-beagle-us-global-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los Beagle son perros activos y atentos, que son mascotas de familia muy leales y amorosas.",
        "acercade":"Cuando socializan y se ejercitan bien, los Beagle son buenos con otras mascotas y niños, lo cual los hace una raza popular de familia. Sin embargo, es importante recordar que los Beagle inicialmente se criaron como perros de caza y que pueden distraerse fácilmente cuando salen a caminar. Esto hace que sean una de las razas de perros más difíciles de entrenar. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":34,
        "raza":"Beagle",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/BCLSxWoBaxEApS7LKRyN/v1/bd140bl-hub-beagle-herrier-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/BSLSxWoBaxEApS7LYRzG/v1/bd140h-hub-beagle-herrier-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"A pesar de su nombre con acento inglés y sus antepasados británicos, el beagle harrier es francés.",
        "acercade":"El barón Gérard, considerado el padre de la raza, priorizó la resistencia y la persistencia al seleccionar las características, de modo que los beagle harrier siempre pudieran seguir la batalla montada en manada sin perder la cohesión. Es por eso que los beagle harrier son fáciles de entrenar y tan entusiastas. Los beagle harrier son una elegante cruza entre dos razas. Estos sabuesos pueden rastrear liebres, zorros, corzos o jabalíes. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"12-13 años"
    },
    {
        "id":35,
        "raza":"Border collie",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/efo9IGYBIYfdNSoCUQiA/v2/bd34bl-border-collie-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/vvpOHWsBIYfdNSoCzxor/v3/bd34h-hub-border-collie-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los border collie son famosos en todo el mundo por sus habilidades con el rebaño.",
        "acercade":"Caracterizados por una gracia, una elegancia y un equilibrio perfectos, además de la combinación de sustancia y resistencia, los border collies son perros inteligentes y leales. Estos perros de trabajo de energía exuberante son compañeros afectuosos. Debido a sus requisitos de ejercicio y entrenamiento, los border collies son mucho más adecuados para propietarios o familias con experiencia en la posesión de una raza de trabajo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":36,
        "raza":"Boyero de Appenzell",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/9iLMxWoBaxEApS7LVBs6/v1/bd129bl-hub-appenzell-cattle-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/9yLMxWoBaxEApS7LYhvp/v1/bd129h-hub-appenzell-cattle-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"A pesar de su popularidad, la reproducción de los boyeros de Appenzell es muy escasa. Solo un programa de crianza muy cuidadoso puede mantener y profundizar las características hereditarias de esta notable raza.",
        "acercade":"Según la tradición, los boyeros de Appenzell se usan para guiar y proteger el ganado y otros animales, así como para proteger la granja. Además, son perros de trabajo versátiles y excelentes mascotas de familia. Pertenecen a una raza tricolor de tamaño mediano, forma cuadrada y buenas proporciones. Estos perros son musculosos, altamente escurridizos y ágiles. Tienen una expresión traviesa característica y suelen ser animados, seguros de sí mismos y muy alegres. Son intrépidos, pero desconfían de los extraños. Se los conoce por ser resueltos, pero también son compañeros maravillosos y muy receptivos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Suiza",
        "tamaño":"Mediano",
        "vida":"12-14 años"
    },
    {
        "id":37,
        "raza":"Braco del Ariege",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/Tfo9x2oBIYfdNSoCyhkw/v1/bd152bl-hub-ariege-pointing-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/SCIEHmsBaxEApS7LAx1L/v5/bd152h-hub-ariege-pointing-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"A pesar de haber reaparecido solo recientemente, el braco del Ariege es en realidad uno de los bracos pirenaicos, aunque es menos conocido que el tipo Gascuña o pirenaico.",
        "acercade":"Estos perros de muestra de montaña del sudoeste de Francia están adaptados a todas las formas de caza. Robustos, dóciles y fáciles de entrenar, son perros poderosos pero magros que exudan vigor. Se buscan en ellos piernas magras, músculos prominentes y líneas bien definidas. Su pelaje blanco, moteado de naranja pálido, a veces con pecas marrones, es señal de un perro distinguido y elegante. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":38,
        "raza":"Braco del Borbonesado",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/Tvo9x2oBIYfdNSoC_BmA/v1/bd153bl-hub-bourbonnais-pointing-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/SSIEHmsBaxEApS7LHx39/v1/bd153h-hub-bourbonnais-pointing-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El braco del Borbonesado tiene la cabeza en forma de pera; ni demasiado ligera ni demasiado pesada, está en perfecta proporción con su cuerpo.",
        "acercade":"En casa, esta raza es dócil y afectuosa, pero cuando está de caza su pasión e inteligencia le permiten adaptarse fácilmente a las presas y terrenos más variados. Estos perros buscan naturalmente olores por encima del suelo, con lo cual muestran una aptitud práctica y precisa para apuntar. El braco del Borbonesado es un perro de tamaño mediano y pelo corto de complexión compacta y musculosa que da la impresión de fuerza y potencia.Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"13-15 años"
    },
    {
        "id":39,
        "raza":"Braco eslovaco de pelo duro",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/tWnlsmoBG95Xk-RBJfaU/v1/bd300bl-hub-wirehaired-slovakian-pointer-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/IvogHmsBIYfdNSoCmxv_/v1/bd300h-hub-wirehaired-slovakian-pointer-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los bracos eslovacos de pelo duro no se han criado durante largo tiempo y se encuentran casi exclusivamente en su país de origen. Los criadores buscan un perro con una complexión robusta, pero liviana.",
        "acercade":"Los bracos eslovacos de pelo duro son perros en especial robustos, vigorosos y versátiles que pueden trabajar en las llanuras, en los bosques y en el agua, cuando buscan y recuperan el animal herido. Estos perros obedientes son fáciles de entrenar. Los bracos eslovacos de pelo duro son perros de trabajo eficientes, con una fuerza moderada, pero de contextura noble. El color base del pelaje de su pelo duro es 'gris'. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Eslovaquia",
        "tamaño":"Mediano",
        "vida":"9-15 años"
    },
    {
        "id":40,
        "raza":"Braco francés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/Wfq2H2YBIYfdNSoCtggQ/v2/bd155bl-braque-francais-pyrenees-type-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/9voEHmsBIYfdNSoCfRoY/v5/bd155h-hub-french-pointing-dog-pyrenean-type-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los bracos franceses, tipo Pirineos son más enérgicos, impulsivos y rápidos en el suelo que los tipo Gascuña y saben cómo conservar la energía para no usarla demasiado pronto.",
        "acercade":"El braco francés es un perro nativo del sur de los Pirineos. Como una raza altamente adaptable, ha encontrado un hogar con cazadores de otras partes de Francia y en el extranjero. El braco francés, tipo Pirineos tiene las mismas características generales que el tipo Gascuña, solo que es más pequeño y liviano. Estos son perros robustos, con bastante musculatura pero livianos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":41,
        "raza":"Braco húngaro de pelo corto",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/NiIzx2oBaxEApS7LmxzA/v1/bd113bl-hub-hungarian-short-haired-pointer-vizsla-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/NyI0x2oBaxEApS7L-hxQ/v1/bd113h-hub-hungarian-short-haired-pointer-vizsla-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los bracos húngaros de pelo corto son perros de caza versátiles, que pueden trabajar en llanuras, bosques o agua.",
        "acercade":"Sus cualidades típicas son una nariz sobresaliente, habilidades de recuperación notables y una habilidad innata para seguir el rastro del olor, incluso cuando nada. Su naturaleza relajada lo hace adecuado para vivir en interiores. Los bracos húngaros de pelo corto son perros delgados y de contextura más bien ligera, que representan la fuerza y la belleza en perfecta armonía. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Hungría",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":42,
        "raza":"Briquet griffon vendeano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/T_o-x2oBIYfdNSoCjxnl/v5/bd158bl-hub-briquet-griffon-vendeen-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/-PoEHmsBIYfdNSoCrRqL/v1/bd158h-hub-briquet-griffon-vendeen-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los briquet griffon vendeanos son perros rápidos y de nariz fina que están preparados para seguir su marca en los arbustos de zarzas. Son muy ágiles en terrenos sinuosos y pueden rastrear con la nariz al viento.",
        "acercade":"Los perros de esta raza robusta muestran mucha iniciativa y resistencia. Deben poder seguir un rastro frío, azuzar la presa y guiar el avance. Son cazadores entusiastas que necesitan una mano firme. Este grifón de tamaño mediano, receptivo y muy terco, es bastante fornido y bien proporcionado. Es la única raza que ha conservado el nombre 'briquet', que significa perro de tamaño mediano. El Conde de Elva comenzó un programa de cría controlado antes de la Primera Guerra Mundial para producir una versión más pequeña y mejorada del gran grifón vendeano. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Mediano",
        "vida":"10-12 años"
    },
    {
        "id":43,
        "raza":"Buhund noruego",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/q2nasmoBG95Xk-RB4_bC/v3/bd252bl-hub-norwegian-buhund-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/FfodHmsBIYfdNSoCoxuq/v1/bd252h-hub-norwegian-buhund-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los buhund noruegos son compañeros maravillosos, que ciertamente es para lo que se crían en su país de origen, aunque tienen la adaptabilidad y la idoneidad para entrenarse a fin de trabajar en diversos campos.",
        "acercade":"Valientes, enérgicos y amistosos, los buhund noruegos son difíciles de encontrar fuera de su país de origen, donde tienen una reputación sobresaliente como compañeros con los que es fácil vivir y a los que es fácil entrenar. Este perro típico tipo spitz es una raza cuadrada que es un poco más pequeña que el promedio. Sus orejas rectas y puntiagudas enfatizan su expresión franca y alerta. La cola la llevan firmemente enroscada sobre la espalda. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Noruega",
        "tamaño":"Mediano",
        "vida":"12-15 años"
    },
    {
        "id":44,
        "raza":"Akita americano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/7SLIxWoBaxEApS7LQRtH/v5/bd124bl-hub-american-akita-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/5_rnHWsBIYfdNSoCABpW/v1/bd124h-hub-american-akita-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Se ha debatido mucho sobre considerar a los akitas americanos como una raza aparte. En la actualidad, la FCI reconoce al akita inu como una raza japonesa y al akita americano como una raza estadounidense.",
        "acercade":"Amistoso, alerta, receptivo, solemne, dócil y valiente: estos son los mejores adjetivos que describen a los akitas americanos. Este poderoso compañero se aprecia por sus instintos innatos de vigilancia. Se recomienda sociabilizarlo desde muy temprana edad. Son relativamente desconfiados con las personas que no conocen y un poco dominantes al relacionarse con otros perros. Son tranquilos, pero tienen una gran presencia; irradian confianza en todo momento. Se dice que su cabeza se parece a la de un oso, en particular a la de un oso polar, pero en realidad hay muchas más similitudes entre ambas especies. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Estados Unidos",
        "tamaño":"Grande",
        "vida":"10-15 años"
    },
    {
        "id":45,
        "raza":"Akita Inu",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/rvo0HWsBIYfdNSoCfxpx/v1/bd22bl-hub-akita-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/sPo4HWsBIYfdNSoCXhoH/v1/bd22h-hub-akita-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los perros Akita Inu valoran mucho la compañía, pero son intensamente independientes y tranquilos, y son capaces de tomar la iniciativa sin vacilar.",
        "acercade":"Estos perros guardianes son grandes y robustos, con mucha personalidad y una aptitud para el atletismo que los hace ideales para realizar largas caminatas y ejercicio. El Akita Inu tiene una expresión noble y digna que lo ha hecho popular en todo el mundo. Salvo por el blanco, todos los colores del pelaje son 'urajiro', lo cual significa que los laterales del hocico, las mejillas, debajo de la mandíbula, el cuello, el pecho, el vientre, la parte inferior de la cola y el interior de las piernas están cubiertos de pelo blanquecino. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Japón",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":46,
        "raza":"Antiguo perro de pastor inglés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/HSIrx2oBaxEApS7LPhxE/v1/bd90bl-hub-old-english-sheepdog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/HyIrx2oBaxEApS7LrhxG/v1/bd90h-hub-old-english-sheepdog-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los antiguos perros de pastor inglés son canes corpulentos y musculosos, con una expresión muy inteligente.",
        "acercade":"Es posible que el antiguo perro de pastor inglés sea una de las razas de aspecto más icónico en todo el mundo y, ciertamente, en su país natal, el Reino Unido. Fuerte y lleno de energía, el antiguo perro de pastor inglés es un perro fiel y confiable, tanto en el trabajo como en el hogar familiar. Además de ser famoso como perro de granja, el antiguo perro de pastor inglés es un perro guardián excelente, gracias a su naturaleza alerta y protectora. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":47,
        "raza":"Basset hound",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/tvpBHWsBIYfdNSoCdxr6/v1/bd29bl-hub-basset-hound-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/t_pCHWsBIYfdNSoCSBpm/v1/bd29h-hub-basset-hound-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Estos tenaces sabuesos muestran una gran resistencia en la caza.",
        "acercade":"Los basset hounds son perros tranquilos que muestran un cariño especial a quienes tienen cerca y nunca son agresivos. Tienen reputación de ser obstinados, pero su carácter travieso les ha ganado admiradores en todo el mundo. Los basset hound son los más pesados y los más poderosos de la categoría de sabuesos, y están clasificados como un perro grande a pesar de su baja estatura. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":48,
        "raza":"Billy",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/DiLVxWoBaxEApS7LVBzY/v1/bd145bl-hub-billy-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/RCL-HWsBaxEApS7LDB3p/v1/bd145h-hub-billy-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los billy tienen una voz hermosa y aguda. Al igual que todos los sabuesos, los billy muestran su vozarrón cuando están siguiendo una marca, lo cual, según los expertos, genera una sinfonía única.",
        "acercade":"Los billies son sabuesos grandes nativos de Haut-Poitou en el centro occidental de Francia. Sus ancestros (perros grandes y blancos) fueron inquilinos frecuentes de las perreras reales en el reinado de Luis XIV. Cuando están más a gusto los billies es siguiendo el rastro de liebres y jabalíes, que es donde se apreciarán mejor sus cualidades. Por tanto, las cualidades más importantes de la raza van de la mano con sus aptitudes de caza. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Grande",
        "vida":"12-15 años"
    },
    {
        "id":49,
        "raza":"Borzoi",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/wvpRHWsBIYfdNSoCJhpA/v1/bd36bl-hub-borzoi-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/6mlRHWsBG95Xk-RB_Phy/v1/bd36h-hub-borzoi-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El nombre Borzoi significa 'veloz' en su país de origen, y cuando se observa la estructura atlética y ligera de esta raza, es fácil ver por qué lleva ese nombre.",
        "acercade":"El Borzoi es una raza leal, afectuosa y confiable que se desarrolla a plenitud en compañía humana, lo cual los convierte en perros fantásticos para familias activas. Sin embargo, este perro no debe tomarse a la ligera. Su gran estatura significa que requieren mucho espacio a su disposición, y el pelaje tan distintivo necesita mucho cuidado. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Rusia",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":50,
        "raza":"Boxer",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/nPq6HGsBIYfdNSoCaBpp/v5/bd8bl-hub-boxer-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/nfq6HGsBIYfdNSoCshoS/v1/bd8h-hub-boxer-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los Boxer siempre han gozado de gran fama por su devoción y lealtad a su familia, así como por su vigilancia y valentía inquebrantable como defensores.",
        "acercade":"Los Boxer son intrépidos, seguros de sí mismos, tranquilos y equilibrados. Aunque no representan ninguna amenaza para su familia, a menudo desconfían de los extraños y no conocen el miedo cuando se irritan. Los Boxer son obedientes, por lo que son fáciles de entrenar. Poco exigentes, limpios y leales, son tan adecuados para un papel familiar y de perro de compañía como para perro de defensa y servicio. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Grande",
        "vida":"9-10 años"
    },
    {
        "id":51,
        "raza":"Boyero de Flandes",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/8GlVHWsBG95Xk-RBDvj7/v1/bd39bl-hub-bouvier-des-flandres-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/8WlVHWsBG95Xk-RBcPjv/v1/bd39h-hub-bouvier-des-flandres-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Tranquilo pero audaz, el boyero de Flandes es un perro inteligente y enérgico.",
        "acercade":"El boyero de Flandes se utilizó originalmente para guiar rebaños, como animal de tiro y para batir mantequilla. Esto cambió con la modernización de los equipos agrícolas y hoy en día el boyero de Flandes se utiliza para vigilar granjas y como perro de defensa. Estos perros de voluntad fuerte son excelentes para dueños experimentados que pueden dedicar tiempo a sus necesidades de entrenamiento y conducta, y aseo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":52,
        "raza":"Braco francés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/QiI-x2oBaxEApS7LKxzk/v1/bd154bl-hub-french-pointing-dog-gascogne-type-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/SiIEHmsBaxEApS7LSh3m/v1/bd154h-hub-french-pointing-dog-gascogne-type-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Reconocido como un cazador nato por usuarios y entusiastas por igual, que incluso afirman que no necesita entrenamiento y conducta.",
        "acercade":"Estos perros de muestra de aspecto noble son poderosos, pero para nada pesados, robustos ni de extremidades fuertes. Las hembras son más delgadas. Su piel es flexible y bastante suelta. El braco francés viene en dos tipos diferentes: el gran tipo Gascuña y el tipo pequeño de los Pirineos. Provienen originalmente del sudoeste de Francia y de los Pirineos centrales, respectivamente, donde permanecieron puros. En las últimas décadas, se han convertido en los perros de muestra franceses más populares, y se dice que el braco marrón original es el antepasado de la mayoría de los perros de muestra europeos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Grande",
        "vida":"12-15 años"
    },
    {
        "id":53,
        "raza":"Braco húngaro de pelo corto",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/dGnCsmoBG95Xk-RBufYo/v3/bd328bl-hub-hungarian-wire-haired-pointer-vizsla-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/ciIjHmsBaxEApS7L2h0P/v1/bd328h-hub-hungarian-wire-haired-pointer-vizsla-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El modo de andar típico del braco húngaro de pelo duro es un trote elegante y relajado, que impulsan las patas traseras mientras que las patas delanteras avanzan. En terrenos llanos, el braco húngaro de pelo duro galopa a un ritmo parejo y cubre una gran cantidad de terreno.",
        "acercade":"Los bracos húngaros de pelo duro son apegados a sus dueños, conscientes de su valor, receptivos y fáciles de entrenar, pero no son aptos para un tratamiento rudo. Mantienen el contacto con su dueño, buscan con pasión y perseverancia, y emplean su excelente nariz y sus habilidades perfectas para señalar. Los bracos húngaros de pelo duro se suelen emplear como perros de terapia, gracias a su naturaleza inteligente y paciente. Sin embargo, necesitan hacer mucho ejercicio debido a sus altos niveles de energía. Esto los hace muy adecuados para muchos deportes caninos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Hungría",
        "tamaño":"Grande",
        "vida":"12-14 años"
    },
    {
        "id":54,
        "raza":"Braco Italiano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/QSI9x2oBaxEApS7LgxwS/v1/bd150bl-hub-italian-pointing-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/RyIDHmsBaxEApS7LzB2m/v1/bd150h-hub-italian-pointing-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Con su estructura ósea y porte de sabueso, el Braco Italiano es una de las razas de perros más antiguas, con menciones en escritos que datan del siglo XV.",
        "acercade":"Robustos y adaptados a todo tipo de caza, los Braco Italiano son perros de muestra confiables con un excelente sentido del olfato, dóciles y fáciles de entrenar. A pesar de sus instintos de caza, estos perros se están convirtiendo en mascotas familiares dulces y afectuosas debido a que son fáciles de mantener, a su paciencia con los niños y su capacidad de quedarse solos en el hogar. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Grande",
        "vida":"12-13 años"
    },
    {
        "id":55,
        "raza":"Cane corso",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/AWlfHWsBG95Xk-RBJfnw/v1/bd47bl-hub-cane-corso-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/AmlgHWsBG95Xk-RBePk7/v1/bd47h-hub-cane-corso-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Estos perros son bastante grandes, macizos y fornidos, pero a la vez sorprende su elegancia.",
        "acercade":"Los cane corsos son muy adaptables, receptivos y ágiles; se utilizan en todo el mundo como guardianes de propiedades y ganado. A primera vista, el cane corso puede parecer intimidante, pero en el fondo es inteligente, entusiasta e increíblemente leal a sus compañeros humanos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":56,
        "raza":"Cazador de alces sueco",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/MiIyx2oBaxEApS7LrBwc/v1/bd110bl-hub-jamthund-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/MyIyx2oBaxEApS7L7xwj/v1/bd110h-hub-jamthund-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Además de cazar alces, los cazadores de alces suecos se empleaban contra osos y linces, por lo que son, indudablemente, perros fuertes y resistentes.",
        "acercade":"También conocido como Jämthund, el cazador de alces sueco es un perro grande y poderoso. A pesar de esto, son perros tranquilos y sociables, que son excelentes compañeros para dueños experimentados. Estos perros se crían para ser un poco independientes por naturaleza, por lo que requieren dueños que puedan establecerse como el 'alfa' del hogar y enseñarle a esta raza a controlar su fuerza y su naturaleza protectora. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Suecia",
        "tamaño":"Grande",
        "vida":"12-13 años"
    },
    {
        "id":57,
        "raza":"Clumber Spaniel",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/2CIqxWoBaxEApS7L9hvQ/v1/bd170bl-hub-clumber-spaniel-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/F_orxWoBIYfdNSoCMxlC/v3/bd170h-hub-clumber-spaniel-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Esta es una de las razas poco frecuentes, aunque tal vez deberían ser más populares por su idoneidad para la vida hogareña, paciencia y simpatía desbocada.",
        "acercade":"Los Clumber Spaniel son estoicos, de gran corazón y muy inteligentes, con una determinación que resalta sus habilidades naturales. Son trabajadores silenciosos que aprovechan su excelente sentido, y también son compañeros estables y seguros, que irradian bondad y dignidad. Estos perros bien equilibrados y de huesos fuertes poseen una expresión pensativa. Son animales activos y encarnan una gran fuerza. Dado que su cuerpo es largo y las patas cortas, los Clumber Spaniel se bambolean cuando caminan, y tanto la parte trasera como la delantera avanzan en línea recta sin esfuerzo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":58,
        "raza":"Cobrador de pelo liso",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/__puwWoBIYfdNSoCPxjl/v3/bd193bl-hub-flat-coated-retriever-adult-sitting?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/VyIYHmsBaxEApS7LAR0v/v1/bd193h-hub-flat-coated-retriever-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los cobradores de pelo liso son perros poderosos, de tamaño mediano, juguetones y llenos de energía.",
        "acercade":"Los cobradores de pelo liso comparten diversas características con otros perros de esta raza, como la sociabilidad con los seres humanos y otros perros, las habilidades naturales de recuperación de las presas y el amor por el agua. Estos afectuosos y enérgicos animales conservan su entusiasmo de cachorro hasta la edad adulta y son más adecuados para familias activas que gustan de disfrutar al aire libre. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Reino Unido",
        "tamaño":"Grande",
        "vida":"10-13 años"
    },
    {
        "id":59,
        "raza":"Coonhound negro y fuego",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/ECLVxWoBaxEApS7L5xy8/v1/bd146bl-hub-black-and-tan-coonhound-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/RiIAHmsBaxEApS7LWh3L/v1/bd146h-hub-black-and-tan-coonhound-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los coonhound negro y fuego se utilizan principalmente para la caza, por lo que toda herida que puedan sufrir se considera honorable.",
        "acercade":"Los coonhounds negro y fuego son perros apacibles, sociables y plácidos que deben ser capaces de trabajar en conjunto con otros perros. Puede que algunos sean un poco retraídos, pero jamás son tímidos ni violentos. La agresión hacia humanos u otros perros es muy indeseable. Su cara expresa bien lo atentos y amistosos que son. Los coonhounds negro y fuego son, ante todo, perros de trabajo, entrenados para rastrear mapaches en el suelo por el olor y obligarlos a refugiarse en los árboles. Los perros de esta raza estadounidense no solo están a la altura de los rigores del invierno y el verano, sino que también pueden sortear los terrenos más difíciles. Su aptitud y coraje también los hacen aptos para rastrear ciervos, osos, pumas y otros animales grandes. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Estados Unidos",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":60,
        "raza":"Dálmata",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/0fqUHWsBIYfdNSoCfRo2/v1/bd55bl-hub-dalmatian-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/0vqVHWsBIYfdNSoCLRqA/v5/bd55h-hub-dalmatian-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los dálmatas son ampliamente conocidos por acompañar y vigilar las cuadrillas de la nobleza tiradas por caballos, los carruajes de viaje y los bomberos.",
        "acercade":"Además de estrellas de la pantalla grande, los dálmatas son perros deportivos versátiles que se adaptan bien a muchas disciplinas diferentes. Los dálmatas son animados, leales, independientes y fáciles de entrenar. Son perros activos a los que les gusta el ejercicio al aire libre y les atrae el agua. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Croacia",
        "tamaño":"Grande",
        "vida":"10-13 años"
    },
    {
        "id":61,
        "raza":"Dogo Argentino",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/3CIvxWoBaxEApS7L5Bua/v1/bd179bl-hub-dogo-argentino-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/APoMHmsBIYfdNSoCiRsR/v4/bd179h-hub-dogo-argentino-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los Dogo Argentino son perros felices, abiertos y amistosos que rara vez ladran, tal vez porque se dan cuenta de que su imponente estatura logra el efecto necesario sin mayor esfuerzo.",
        "acercade":"El Dogo Argentino es un perro compacto y musculoso de patas largas. Son animales inteligentes con reacciones rápidas, aunque su andar es tranquilo pero firme y expresivo. Estos perros leales y afectuosos son de un color blanco impresionante. En resumen, esta raza posee la destreza física de un atleta natural. En climas tropicales, su pelaje es fino y escaso, que deja entrever áreas pigmentadas. En climas fríos, su pelo es más grueso y más denso, y puede tener una subcapa de pelo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Argentina",
        "tamaño":"Grande",
        "vida":"10-12 años"
    },
    {
        "id":62,
        "raza":"Espinone",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/cfrLsmoBIYfdNSoCQBi4/v1/bd309bl-hub-italian-spinone-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/I_oiHmsBIYfdNSoCQBtP/v5/bd309h-hub-italian-spinone-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Estos perros incansables no tienen problemas en meterse entre las espinas o agua congelada para hacer su trabajo.",
        "acercade":"Naturalmente sociables, dóciles y pacientes, los Espinone son cazadores hábiles en cualquier terreno. Son excelentes perdigueros, además de perros de muestra, y se mueven rápidamente con un trote amplio. En una encuesta para amantes de perros en Italia, el Espinone resultó el perro de compañía ideal, sin desmerecer sus habilidades de caza. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Grande",
        "vida":"12-14 años"
    },
    {
        "id":63,
        "raza":"Boyero de Berna",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/qPotHWsBIYfdNSoCPRp3/v1/bd18bl-hub-bernese-mountain-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/qfouHWsBIYfdNSoCuhpy/v1/bd18h-hub-bernese-mountain-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los boyeros de Berna son populares por su hermoso pelaje y carácter bonachón.",
        "acercade":"Originalmente usados como perros guardianes y de ganado en granjas en la región de Berna, Suiza, los boyeros de Berna son animales de trabajo versátiles y mascotas familiares muy queridas. Su impresionante pelaje tricolor y su gran adaptabilidad les han significado un lugar en el corazón de las familias de todo el mundo. Bien equilibrados, atentos, vigilantes y valientes en situaciones cotidianas, son mansos y leales con las personas que conocen, mientras que son seguros de sí mismos y tranquilos con los extraños. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Suiza",
        "tamaño":"Gigantes",
        "vida":"8 años"
    },
    {
        "id":64,
        "raza":"Dogo de Burdeos",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/1_rEHWsBIYfdNSoC7hrn/v1/bd57bl-hub-dogue-de-bordeaux-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/JiLFHWsBaxEApS7LNR0J/v1/bd57h-hub-dogue-de-bordeaux-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El dogo de Burdeos es la raza más antigua de todos los perros franceses y se cree que se originó por allá por el siglo XIV.",
        "acercade":"El dogo de Burdeos es vigilante y valiente, lo que lo convierte en un excepcional perro guardián. Estos perros son excelentes compañeros de sus dueños y se vuelven muy apegados a su familia. Son afectuosos con los niños y tolerantes con otros perros. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Gigantes",
        "vida":"8-10 años"
    },
    {
        "id":65,
        "raza":"Dogo del Tíbet",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/NCIzx2oBaxEApS7LDhy3/v1/bd111bl-hub-tibetan-mastiff-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/NSIzx2oBaxEApS7LPRzY/v1/bd111h-hub-tibetan-mastiff-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Algunos de los primeros dogos del Tíbet en Europa se exhibieron en el zoológico de Berlín, donde nació una camada en 1878.",
        "acercade":"Los dogos del Tíbet son gigantes enérgicos y fornidos. Estos perros de aspecto sobrio combinan una fuerza imponente con una resistencia que les permite trabajar en cualquier clima. Independientes e imponentes, los dogos del Tíbet son muy leales a su familia y protegen su territorio. Se demoran en madurar; las hembras tardan de dos a tres años en desarrollarse físicamente por completo, mientras que los machos tardan, al menos, cuatro años. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Tíbet",
        "tamaño":"Gigantes",
        "vida":"10-15 años"
    },
    {
        "id":66,
        "raza":"Gran danés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/4vrWHWsBIYfdNSoCshrb/v1/bd66bl-hub-great-dane-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/LiLXHWsBaxEApS7LXR2i/v1/bd66h-hub-great-dane-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El gran danés combina orgullo, poder y entereza en un solo ejemplar.",
        "acercade":"Con su contextura armoniosa y su rostro expresivo, los perros de esta raza son dóciles gigantes. Los ejemplares de gran danés son alegres, amorosos y apegados a sus compañeros humanos, sobre todo a los niños, aunque desconfían de los extraños. Un gran danés seguro de sí mismo, tranquilo y receptivo es un perro familiar muy tolerante y con poca agresividad. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Gigantes",
        "vida":"8-10 años"
    },
    {
        "id":67,
        "raza":"Landseer",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/pGnWsmoBG95Xk-RB2fZ6/v1/bd241bl-hub-landseer-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/YCIcHmsBaxEApS7LjB2v/v5/bd241h-hub-landseer-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Son perros gigantes con pies felinos, ya que los dedos están unidos por una membrana interdigital, lo que explica por qué son tan buenos en el agua.",
        "acercade":"Los landseers son perros grandes y robustos de buenas proporciones. Las patas son más altas que las de sus primos, los terranovas negros. Naturalmente protector, el landseer ha sido conocido por actuar como niñera de los niños de la familia sin dudarlo, y defenderá a su familia de cualquier amenaza. Como tales, también son fantásticos perros guardianes. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Gigantes",
        "vida":"9-11 años"
    },
    {
        "id":68,
        "raza":"Lebrel irlandés",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/Jvomx2oBIYfdNSoCOBlg/v1/bd76bl-hub-irish-wolfhound-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/J_omx2oBIYfdNSoCbhkq/v1/bd76h-hub-irish-wolfhound-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"A pesar de que el lebrel irlandés se desarrolló para cazar lobos, esta raza es tan dócil como un perro de compañía.",
        "acercade":"Hasta el final del siglo XVII, estos perros se utilizaron en Irlanda para cazar lobos y ciervos. Hoy en día, son perros de compañía de renombre. Sin duda, no tan pesados ni robustos como el gran danés, los lebreles irlandeses todavía son perros muy grandes e imponentes con muchos músculos. Los lebreles irlandeses son buenos perros guardianes, dispuestos a proteger a su familia humana de cualquier amenaza. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Irlanda",
        "tamaño":"Gigantes",
        "vida":"8-10 años"
    },
    {
        "id":69,
        "raza":"Leonberger",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/bvrKsmoBIYfdNSoCIBhP/v1/bd83bl-hub-leonberger-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/iWnKsmoBG95Xk-RBSfYa/v1/bd83h-hub-leonberger-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Al desarrollar el leonberger, se cree que el objetivo del criador era desarrollar un perro que se asemejara al león en el escudo de Leonberg.",
        "acercade":"A pesar de su intimidante tamaño, el leonberger en realidad es un perro dócil y amoroso que resulta un excelente compañero de familia. Son amistosos con los niños y pacientes con otros animales en el hogar. El leonberger es inteligente, resistente y observador, por lo que resultan perros guardianes naturales que identifican rápidamente a los extraños y alertan a sus dueños sobre cualquier actividad inusual. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Gigantes",
        "vida":"8-9 años"
    },
    {
        "id":70,
        "raza":"Mastín del Pirineo",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/-_pyH2YBIYfdNSoCXgfZ/v2/bd280bl-pyrenean-mastiff-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/HPofHmsBIYfdNSoClBv1/v3/bd280h-hub-pyrenean-mastiff-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Aunque no se sabe a ciencia cierta, se cree ampliamente que la raza desciende de los perros molosoides que llegaron a España desde Sumeria y Asiria de la mano de los fenicios, hace más de 3000 años.",
        "acercade":"Los mastines del Pirineo son ideales para proteger a las personas y las propiedades rurales. Estos perros fáciles de entrenar son amistosos, tranquilos, nobles y especialmente inteligentes. Los desconocidos se encontrarán con un perro valiente y feroz, que se mantiene firme en todo momento; otros perros se encontrarán con una criatura bondadosa, que es plenamente consciente de su fuerza. Los mastines del Pirineo son luchadores consumados si es necesario y aprovechan todas las habilidades que adquirieron como raza durante siglos de combate contra los lobos. Su ladrido es profundo y grave, con expresión alerta. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"España",
        "tamaño":"Gigantes",
        "vida":"10-12 años"
    },
    {
        "id":71,
        "raza":"Mastín Español",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/Qvowx2oBIYfdNSoCyxk3/v1/bd106bl-hub-spanish-mastiff-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/LSIwx2oBaxEApS7L9hwA/v1/bd106h-hub-spanish-mastiff-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"El Mastín Español tiene un ladrido grave y profundo, que se puede escuchar desde una distancia considerable.",
        "acercade":"Los Mastín Español están estrechamente relacionados con el ciclo estacional de traslado del ganado de una tierra para pastar a otra, especialmente en el caso de las ovejas, a las cuales protegen de los lobos y otros depredadores desde la Edad Media. En la actualidad, también se emplean para proteger propiedades y defender a las personas. Estos animales son muy inteligentes, pero no carecen de belleza y ambos se expresan en su mirada. Robustos, amorosos, tranquilos y nobles, no se dejan intimidar por los animales que representan una amenaza o por las personas que no les son familiares, especialmente cuando tienen el deber de proteger y defender. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"España",
        "tamaño":"Gigantes",
        "vida":"10-11 años"
    },
    {
        "id":72,
        "raza":"Mastín napolitano",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/jvrasmoBIYfdNSoCIxgE/v1/bd250bl-hub-neopolitan-mastiff-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/qWnasmoBG95Xk-RBSfYL/v1/bd250h-hub-neopolitan-mastiff-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los mastines napolitanos no solo tienen un aspecto característico, sino que también se mueven de una manera muy original. Al caminar, se desplazan a un ritmo medido, y no como un oso o un felino grande.",
        "acercade":"Inteligentes, estables y leales, carentes de agresividad o irritabilidad a menos que los provoquen, los mastines napolitanos son perros majestuosos y nobles, que conllevan una amenaza más bien implícita, lo que los hace muy adecuados para tareas de guardia y protección. Los mastines napolitanos son una de las razas más antiguas nativas de Italia. A pesar de su tamaño y su apariencia imponentes, estos perros son famosos por ser increíblemente dóciles y tranquilos. Sin embargo, debido a su tamaño y a su fuerza, no son adecuados para los dueños primerizos. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Italia",
        "tamaño":"Gigantes",
        "vida":"8-10 años"
    },
    {
        "id":73,
        "raza":"Perro de la sierra de la Estrela",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/4PrQHWsBIYfdNSoC5Brp/v1/bd63bl-hub-estrela-mountain-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/LCLUHWsBaxEApS7Lch1q/v1/bd63h-hub-estrela-mountain-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los perros de la sierra de la Estrela son dinámicos e imponentes. Su expresión es alerta, tranquila e inteligente.",
        "acercade":"Los perros de la sierra de la Estrela son perros molosoides tipo mastín inglés. Bien equilibrados, compactos y resistentes, se ganan el respeto de los extraños a través de su comportamiento firme y reservado. Son notablemente obedientes con su dueño y son compañeros leales e inseparables. Trabajan sin descanso para proteger al rebaño de los lobos y los cuatreros. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Portugal",
        "tamaño":"Gigantes",
        "vida":"10-12 años"
    },
    {
        "id":74,
        "raza":"Perro de montaña de los Pirineos",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/LyLXHWsBaxEApS7L6x1x/v1/bd67bl-hub-pyrenean-mountain-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/fGmJMWsBG95Xk-RBbvk9/v1/bd67h-hub-pyreneen-mountain-dog-adult-black-and-white?w=640&h=640&auto=compress&fm=jpg&auto=compress",
        "descripcion":"Los perros de montaña de los Pirineos son pastores tenaces que pueden detener a osos y lobos, un papel que siguen desempeñando hoy en día.",
        "acercade":"También conocido como gran pirineo, el perro de montaña de los Pirineos ha sido criado en primer lugar para proteger a los rebaños. Son fuertes y ágiles, además de dóciles y apegados a sus líderes. Usados como perros mensajeros y de carga por el ejército francés durante la Segunda Guerra Mundial, ahora son populares en todos los continentes, desde América del Norte hasta Australasia. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Francia",
        "tamaño":"Gigantes",
        "vida":"10-12 años"
    },
    {
        "id":75,
        "raza":"Perro de pastor Kangal",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/2mk8HWsBG95Xk-RByPhS/v1/bd25bl-hub-kangal-shepherd-dog-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/f2mKMWsBG95Xk-RBI_np/v1/bd25bl-hub-kangal-shepherd-dog-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"Los perros de pastor Kangal son un encanto de ver en acción: dan pasos largos y flexibles que denotan gran poder, como un gato grande acechando a su presa.",
        "acercade":"Al principio, estos perros grandes y poderosos se utilizaban para proteger ovejas en Anatolia. Son perros trabajadores capaces de soportar condiciones climáticas extremas, desde altas temperaturas de verano hasta temperaturas bajo cero en invierno. Estos perros grandes y robustos son resistentes y rápidos, bien educados y audaces, pero no agresivos. Son fieles y afectuosos con sus dueños durante toda la vida. Cuando son adultos, desconfían de los extraños. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Turquía",
        "tamaño":"Gigantes",
        "vida":"10-13 años"
    },
    {
        "id":76,
        "raza":"Rottweiler",
        "thumbnail":"https://cdn.royalcanin-weshare-online.io/z2krHWsBG95Xk-RBIvja/v1/bd14bl-hub-rottweiler-adult-standing?w=320&fm=jpg&auto=compress",
        "imagen":"https://cdn.royalcanin-weshare-online.io/0GkrHWsBG95Xk-RBifgR/v5/bd14h-hub-rottweiler-adult-black-and-white?w=640&fm=jpg&auto=compress",
        "descripcion":"A pesar de su tamaño y su temible reputación, el rottweiler tiene un temperamento afectuoso, obediente y dócil.",
        "acercade":"Los rottweiler son perros grandes, musculosos y activos, que siempre están alertas a lo que sucede a su alrededor. A pesar de que puede llevarles un tiempo entrar en confianza con los desconocidos, son mascotas de familia leales y gratificantes. Los rottweiler comenzaron como perros de ganado que llevaban a los rebaños hasta los grandes mercados de ganado del sur de Alemania; sin embargo, en las últimas décadas, se han convertido en uno de los perros de defensa más populares del mundo. Fuente: hechos y características clave obtenidos de la Fédération Cynologique Internationale (FCI) y royalcanin.com.",
        "pais":"Alemania",
        "tamaño":"Gigantes",
        "vida":"10-12 años"
    }
]

export function getAllPerros(){
    return perros;
}